name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Check if current version has a tag already
      id: check_tag
      run: |
        version=$(grep -o '"version": "[^"]*"' mpackage.json | cut -d'"' -f4)
        git show-ref --tags --quiet --verify "refs/tags/${{ env.version }}" >> tag_exists
        echo "tag_exists=$tag_exists" >> "$GITHUB_ENV"

        

