name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
        git fetch --tags
        git show-ref --tags --quiet --verify "refs/tags/${{ env.version }}" >> tag_exists
        echo "tag_exists=$tag_exists" >> "$GITHUB_ENV"

