name: Create Release

on: workflow_dispatch

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract version from mpackage.json
      id: get_version
      run: |
        version=$(grep -o '"version": "[^"]*"' mpackage.json | cut -d'"' -f4)
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Check if release tag exists
      id: check_tag
      run: |
        git fetch --tags
        if git rev-parse --quiet --verify "refs/tags/v${{ env.GITHUB_STATE.version }}" >/dev/null; then
          echo "{tag_exists}={true}" >> $GITHUB_STATE
        else
          echo "{tag_exists}={false}" >> $GITHUB_STATE
        fi

    - name: Create release
      id: create_release
      if: env.GITHUB_STATE.tag_exists == 'false'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag -a "v${{ env.GITHUB_STATE.version }}" -m "Release v${{ env.GITHUB_STATE.version }}"
        git push origin "v${{ env.GITHUB_STATE.version }}"
        
