name: Create Release

on: workflow_dispatch

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract version from package.json
      id: get_version
      run: |
        version=$(grep -o '"version": "[^"]*"' mpackage.json | cut -d'"' -f4)
        echo "version=${version}" >> $GITHUB_STATE

    - name: Check if release tag exists
      id: check_tag
      run: |
        git fetch --tags
        if git rev-parse --quiet --verify "refs/tags/v${{ env.GITHUB_STATE_version }}" >/dev/null; then
          echo "::set-output name=tag_exists::true" >> $GITHUB_OUTPUT
        else
          echo "::set-output name=tag_exists::false" >> $GITHUB_OUTPUT
        fi

    - name: Create release
      id: create_release
      if: env.GITHUB_OUTPUT_tag_exists == 'false'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag -a "v${{ env.GITHUB_STATE_version }}" -m "Release v${{ env.GITHUB_STATE_version }}"
        git push origin "v${{ env.GITHUB_STATE_version }}"
        
