name: Create Release

on: push

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract version from mpackage.json
      id: get_version
      run: |
        version=$(grep -o '"version": "[^"]*"' mpackage.json | cut -d'"' -f4)
        echo "version=$version" >> "$GITHUB_ENV"

    - name: Check if release tag exists
      id: check_tag
      run: |
        git fetch --tags
        if git show-ref --tags --quiet --verify "refs/tags/${{ env.version }}"; then
          echo "tag_exists=true" >> "$GITHUB_ENV"
        else
          echo "tag_exists=false" >> "$GITHUB_ENV"
        fi

    - name: Create Release
      id: create_release
      if: env.tag_exists == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ env.version }}
        body: |
          Version ${{ env.version }}
        draft: false
        prerelease: false
