name: Create Release

on: workflow_dispatch

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract version from mpackage.json
      id: get_version
      run: |
        version=$(grep -o '"version": "[^"]*"' mpackage.json | cut -d'"' -f4)
        echo "version=$version" >> "$GITHUB_ENV"

    - name: Check if release tag exists
      id: check_tag
      run: |
        git fetch --tags
        if git show-ref --tags --quiet --verify "refs/tags/${{ env.version }}"; then
          echo "tag_exists=true" >> "$GITHUB_ENV"
        else
          echo "tag_exists=false" >> "$GITHUB_ENV"
        fi

    - name: Create release
      id: create_release
      if: env.tag_exists == 'false'
      run: |
        echo "Creating new release: ${{ env.version }} "
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag -a "v${{ env.version }}" -m "Release v${{ env.version }}"
        git push origin "v${{ env.version }}"
        
