name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get current version from mpackage.json
      id: get_version
      run: echo "::set-output name=version::$(node -p "require('./mpackage.json').version")"

    - name: Check if release tag exists
      id: check_tag
      run: |
        git fetch --tags
        if git rev-parse "refs/tags/v${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
          echo "::set-output name=tag_exists::true"
        else
          echo "::set-output name=tag_exists::false"
        fi

    - name: Create release
      id: create_release
      needs: check_tag
      if: steps.check_tag.outputs.tag_exists == 'false'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag -a "v${{ steps.get_version.outputs.version }}" -m "Release v${{ steps.get_version.outputs.version }}"
        git push origin "v${{ steps.get_version.outputs.version }}"

    - name: Output release URL
      if: steps.create_release.outputs.id != ''
      run: echo "Release created: https://github.com/${{ github.repository }}/releases/tag/v${{ steps.get_version.outputs.version }}"
      
